--$$ Conversation
-- Autogenerated File - please do not edit

_namespace = "CONVERSATIONS"
_id = "THE_GIFT_AND_THE_GRAIN_2"

EntryPoint = "TheGiftAndTheGrain2_Start"
boss = nil
cash = 2000
racket = nil
neighborhoodName = nil
persuasion = 70
fixer = nil
function onStart()


        racket = them.memory.GiftAndTheGrain_Bar
        neighborhoodName = racket:getLocation().name
    
    BRScript:SelectTalkStageFromMemory()
end

function Quote_Intro()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_Intro_say") --$ Can I help you with something?
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Intro_option1", {Quote_IntroResults, "option1"}, nil, nil, nil) --$ Charly Flint? I have it on good authority that you're trying to muscle in on my precinct.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Intro_option2", {Quote_IntroResults, "option2"}, nil, nil, nil) --$ Never mind
end

function Quote_IntroResults(optionResult)
    if (optionResult == "option1") then
        return Quote_WhosSpeaking()
    end
    if (optionResult == "option2") then
        return Quote_Leave()
    end
end

function Quote_WhosSpeaking()
    if BRScript:YouArePlayerBoss() then
        return Quote_Boss()
    else
        return Quote_Gangster()
    end
end

function Quote_Boss()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_Boss_say") --$ Shit, you're {you:name}. Look, you weren't supposed to find out. I mean, I didn't think you'd notice a few sacks. Are we gonna have a problem here?
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Boss_option1", {Quote_BossResults, "option1"}, nil, nil, nil) --$ Is it true you're some kind of genius?
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Boss_option2", {Quote_BossResults, "option2"}, nil, nil, nil) --$ Not if you come work for me.
end

function Quote_BossResults(optionResult)
    if (optionResult == "option1") then
        return Quote_A2()
    end
    if (optionResult == "option2") then
        return Quote_A3()
    end
end

function Quote_Gangster()
    boss = you.faction.boss
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_Gangster_say") --$ Shit, you're {you:name}. Look, you weren't supposed to find out. I mean, I didn't think you'd notice a few sacks. Are we gonna have a problem here?
    option({"$THE_GIFT_AND_THE_GRAIN_2_Quote_Gangster_option1", boss}, {Quote_GangsterResults, "option1"}, nil, nil, nil) --$ I work on behalf of {0:firstName}. Is it true you're some kind of genius?
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Gangster_option2", {Quote_GangsterResults, "option2"}, nil, nil, nil) --$ Not if you come work for us.
end

function Quote_GangsterResults(optionResult)
    if (optionResult == "option1") then
        return Quote_A2()
    end
    if (optionResult == "option2") then
        return Quote_A3()
    end
end

function Quote_A2()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_A2_say") --$ I read a couple of chemistry books, yeah. Turns out I'm a natural at this brewing shit. My method of malting is becoming famous around here.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_A2_option1", {Quote_A2Results, "option1"}, nil, nil, nil) --$ You're modest too... You looking for a job?
end

function Quote_A2Results(optionResult)
    if (optionResult == "option1") then
        return Quote_A3()
    end
end

function Quote_A3()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_A3_say") --$ No way, I'm studying to get a scholarship. Once I go to college I'll be leaving this place behind.
    option({"$THE_GIFT_AND_THE_GRAIN_2_Quote_A3_option1", cash}, {Quote_A3Results, "option1"},  not  not BRScript:PlayerCanAfford(cash), nil, nil) --$ [GIVE {0:C0}] I'll give you a scholarship right now if you come work for me. Not many can say they earn money while they go to school.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_A3_option2", {Quote_A3Results, "option2"}, nil, nil, nil) --$ [PERSUASION] All it takes is one call to the cops in my pocket and they'll come down hard on you for stealing from me.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_A3_option3", {Quote_A3Results, "option3"}, nil, nil, nil) --$ Let me think about it and get back to you.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_A3_option4", {Quote_A3Results, "option4"}, nil, nil, nil) --$ [INTIMIDATION] Not really giving you the option
end

function Quote_A3Results(optionResult)
    if (optionResult == "option1") then
        return Quote_B1()
    end
    if (optionResult == "option2") then
        BRScript:GOTOPersuasionCheck(persuasion, "B2", "B3")
    end
    if (optionResult == "option3") then
        them.memory.talkStage = "Quote_Return"
        return Quote_Leave()
    end
    if (optionResult == "option4") then
        BRScript:GOTOIntimidationCheck("High", "IntimidationSuccess", "IntimidationFailure")
    end
end

function Quote_B1()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_B1_say") --$ Alright look, any old mug can run a brewery. It takes skill to be a maltster, that's what I am. I treat the grain to get the most out of the product. You want to get into malting, I'll help you out.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_B1_option1", {Quote_B1Results, "option1"}, nil, nil, nil) --$ Deal.
end

function Quote_B1Results(optionResult)
    BRScript:PlayerSubtractCash(cash, "CASH.FAVOR")
    if (optionResult == "option1") then
        return Quote_SetLeave()
    end
end

function Quote_B2()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_B2_say") --$ [SUCCESS] Okay, okay, I'll do the malting for you, alright? Help you get the most out of your breweries by treating the grain. C'mon, there's no need to get the cops involved.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_B2_option1", {Quote_B2Results, "option1"}, nil, nil, nil) --$ Good. I knew you were too smart to pass up a good opportunity.
end

function Quote_B2Results(optionResult)
    if (optionResult == "option1") then
        return Quote_SetLeave()
    end
end

function Quote_B3()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_B3_say") --$ [FAILURE] Yeah right. If the cops around here get a sniff of the piss they were drinking before I came along, any charge against me will be dropped. 
    option({"$THE_GIFT_AND_THE_GRAIN_2_Quote_B3_option1", cash}, {Quote_B3Results, "option1"},  not  not BRScript:PlayerCanAfford(cash), nil, nil) --$ [GIVE {0:C0}] Fine. How about I give you a scholarship then and you work for me while you go to college?
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_B3_option2", {Quote_B3Results, "option2"}, nil, nil, nil) --$ So what's it going to take for you to work for me?
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_B3_option3", {Quote_B3Results, "option3"}, nil, nil, nil) --$ Let me think about it and get back to you.
end

function Quote_B3Results(optionResult)
    them.memory.GiftAndGrain_FailedPersuasionCheck = true
    if (optionResult == "option1") then
        return Quote_B1()
    end
    if (optionResult == "option2") then
        return Quote_C1()
    end
    if (optionResult == "option3") then
        them.memory.talkStage = "Quote_Return"
        return Quote_Leave()
    end
end

function Quote_IntimidationSuccess()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_IntimidationSuccess_say") --$ $THE_GIFT_AND_THE_GRAIN_2_Quote_B2_say
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_IntimidationSuccess_option1", {Quote_IntimidationSuccessResults, "option1"}, nil, nil, nil) --$ $THE_GIFT_AND_THE_GRAIN_2_Quote_B2_option1
end

function Quote_IntimidationSuccessResults(optionResult)
    if (optionResult == "option1") then
        return Quote_SetLeave()
    end
end

function Quote_IntimidationFailure()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_IntimidationFailure_say") --$ [FAILURE] Hey no one talks to me that way!
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_IntimidationFailure_option1", {Quote_IntimidationFailureResults, "option1"}, nil, nil, nil) --$ [Begin Combat] Fine. Be that way
end

function Quote_IntimidationFailureResults(optionResult)
    BRScript:MakeNPCCombat(them, false)
    BRScript:AddStateToCharacter(them, "PlotArmor")
    BRScript:AddStateToCharacter(them, "GuardIfFlee")
    fact.GiftAndTheGrain_AttackedCharly = true
    return Quote_TargetStartsCombat()
end

function Quote_C1()
    fixer = BRScript:PlayerHasRPCWithProfession("Fixer")
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_C1_say") --$ I know you're a {you:gender?man|woman|boss} who can get things done. There's a huge development planned for these parts, and they want to level my father's home to make way for it. We haven't got the means to fight it off much longer. If you could somehow talk the contractor out of it, I'd be open to work for you.
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_C1_option1", {Quote_C1Results, "option1"}, nil, nil, nil) --$ Say no more. You know where this contractor is?
    if not BRScript:YouHaveProfession("Fixer") then
        option({"$THE_GIFT_AND_THE_GRAIN_2_Quote_C1_option2", fixer}, {Quote_C1Results, "option2"},  not  not BRScript:PlayerHasRPCWithProfession("Fixer"), nil, nil) --$ [FIXER] We have a fixer in our crew that handles stuff like this. {0:gender?He'll|She'll|They'll} make some calls. It's handled. So?
    end
    if not  not BRScript:YouHaveProfession("Fixer") then
        option("$THE_GIFT_AND_THE_GRAIN_2_Quote_C1_option3", {Quote_C1Results, "option3"}, nil, nil, nil) --$ [FIXER] I'm a fixer, you know. I'll call some people. Consider it done. So?
    end
end

function Quote_C1Results(optionResult)
    if (optionResult == "option1") then
        return Quote_C2()
    end
    if (optionResult == "option2") then
        return Quote_B1()
    end
    if (optionResult == "option3") then
        return Quote_B1()
    end
end

function Quote_C2()
    say({"$THE_GIFT_AND_THE_GRAIN_2_Quote_C2_say", racket, neighborhoodName}) --$ He's usually in {0:name} over in {1} after office hours. Be warned, he likes to think he's a gangster too...
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_C2_option1", {Quote_C2Results, "option1"}, nil, nil, nil) --$ Leave it to me.
end

function Quote_C2Results(optionResult)
    fact.GiftAndTheGrain_TalkedToCharly = 1
    them.memory.talkStage = "Quote_C2"
    if (optionResult == "option1") then
        return Quote_Leave()
    end
end

function Quote_Return()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_Return_say") --$ Oh, it's you again. What do you want?
    option({"$THE_GIFT_AND_THE_GRAIN_2_Quote_Return_option1", cash}, {Quote_ReturnResults, "option1"},  not  not BRScript:PlayerCanAfford(cash), nil, nil) --$ [GIVE {0:C0}] I'll give a scholarship right now, if you come work for me.
    if not them.memory.GiftAndGrain_FailedPersuasionCheck then
        option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Return_option2", {Quote_ReturnResults, "option2"}, nil, nil, nil) --$ [PERSUASION] All it takes is one call to the cops in my pocket and they'll come down hard on you for stealing from me.
    end
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Return_option3", {Quote_ReturnResults, "option3"}, nil, nil, nil) --$ So what's it going to take for you to work for me?
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Return_option4", {Quote_ReturnResults, "option4"}, nil, nil, nil) --$ Let me think about it and get back to you.
end

function Quote_ReturnResults(optionResult)
    if (optionResult == "option1") then
        return Quote_B1()
    end
    if (optionResult == "option2") then
        BRScript:GOTOPersuasionCheck(persuasion, "B2", "B3")
    end
    if (optionResult == "option3") then
        return Quote_C1()
    end
    if (optionResult == "option4") then
        return Quote_Leave()
    end
end

function Quote_Left()
    say("$THE_GIFT_AND_THE_GRAIN_2_Quote_Left_say") --$ $THE_GIFT_AND_THE_GRAIN_2_Quote_B1_say
    option("$THE_GIFT_AND_THE_GRAIN_2_Quote_Left_option1", {Quote_LeftResults, "option1"}, nil, nil, nil) --$ $THE_GIFT_AND_THE_GRAIN_2_Quote_B1_option1
end

function Quote_LeftResults(optionResult)
    return Quote_Leave()
end

function Quote_SetLeave()
    fact.GiftAndTheGrain_TalkedToCharly = 2
    them.memory.talkStage = "Quote_Left"
    return Quote_Leave()
end

