--$$ Conversation
-- Autogenerated File - please do not edit

_namespace = "CONVERSATIONS"
_id = "THE_GIFT_AND_THE_GRAIN_4"

EntryPoint = "TheGiftAndTheGrain4_Start"
MatchingRules =
{
    function() return ( not fact.GiftAndTheGrain_AttackedCharly) end,
}

function onStart()
    BRScript:SelectFromTalkStageOrEntry()
end

function Quote_Intro()
    say("$THE_GIFT_AND_THE_GRAIN_4_Quote_Intro_say") --$ You didn't waste any time. You must be eager.
    option("$THE_GIFT_AND_THE_GRAIN_4_Quote_Intro_option1", {Quote_IntroResults, "option1"}, nil, nil, nil) --$ That development contract has been torn up. It's not going to be a problem anymore.
    option("$THE_GIFT_AND_THE_GRAIN_4_Quote_Intro_option2", {Quote_IntroResults, "option2"}, nil, nil, nil) --$ Never mind
end

function Quote_IntroResults(optionResult)
    if (optionResult == "option1") then
        return Quote_A1()
    end
    if (optionResult == "option2") then
        return Quote_Leave()
    end
end

function Quote_A1()
    say("$THE_GIFT_AND_THE_GRAIN_4_Quote_A1_say") --$ Thanks. Alright look, any old mug can run a brewery. It takes skill to be a maltster, that's what I am. I treat the grain to get the most out of the product. You want to get into malting, I'll help you out.
    option("$THE_GIFT_AND_THE_GRAIN_4_Quote_A1_option1", {Quote_A1Results, "option1"}, nil, nil, nil) --$ Good, I knew this would work out.
end

function Quote_A1Results(optionResult)
    if (optionResult == "option1") then
        return Quote_SetLeave()
    end
end

function Quote_Left()
    say("$THE_GIFT_AND_THE_GRAIN_4_Quote_Left_say") --$ $THE_GIFT_AND_THE_GRAIN_4_Quote_A1_say
    option("$THE_GIFT_AND_THE_GRAIN_4_Quote_Left_option1", {Quote_LeftResults, "option1"}, nil, nil, nil) --$ $THE_GIFT_AND_THE_GRAIN_4_Quote_A1_option1
end

function Quote_LeftResults(optionResult)
    return Quote_Leave()
end

function Quote_SetLeave()
    fact.GiftAndTheGrain_ReturnedToCharly = true
    them.memory.talkStage = "Quote_Left"
    return Quote_Leave()
end

