--$$ Conversation
-- Autogenerated File - please do not edit

_namespace = "CONVERSATIONS"
_id = "THE_GIFT_AND_THE_GRAIN_4A"

EntryPoint = "TheGiftAndTheGrain4_Start"
MatchingRules =
{
    function() return (fact.GiftAndTheGrain_AttackedCharly) end,
}

function onStart()
    BRScript:SelectFromTalkStageOrEntry()
end

function Quote_Intro()
    say("$THE_GIFT_AND_THE_GRAIN_4A_Quote_Intro_say") --$ Okay, okay I respsect your offer. I'll work for you.
    option("$THE_GIFT_AND_THE_GRAIN_4A_Quote_Intro_option1", {Quote_IntroResults, "option1"}, nil, nil, nil) --$ Good, I knew this would work out.
end

function Quote_IntroResults(optionResult)
    if (optionResult == "option1") then
        return Quote_SetLeave()
    end
end

function Quote_SetLeave()
    fact.GiftAndTheGrain_ReturnedToCharly = true
    them.memory.talkStage = "Quote_Left"
    return Quote_Leave()
end

